- name: Add acme group
  group:
    name: acme

- name: Add acme user
  user: 
    name: acme
    group: acme
    groups:
      - www-data
    system: true
    nologin: true

- name: Download acme.sh
  get_url: https://raw.githubusercontent.com/acmesh-official/acme.sh/master/acme.sh
  dest: /usr/local/acme.sh
  mode: +x

- name: Set default acme.sh Server
  command: acme.sh --set-default-ca --server zerossl
  become: true
  become_user: acme

- name: Add directories
  file:
    path: "{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    recurse: true
    mode: 775
  with_items:
    - /var/www/letsencrypt/.well-known/acme-challenge
    - /etc/letsencrypt/{{ item.key }}/live
  with_dict: "{{ nginx_revproxy_sites }}"

- name: Create new Certificates
  command: |
    acme.sh --issue \
    -d {{ item.value.domains | join(' -d ') }} \
    --server zerossl \
    --keylength 4096 \
    -w /var/www/letsencrypt \
    --key-file /etc/letsencrypt/{{ item.key }}/live/key.pem \
    --ca-file /etc/letsencrypt/{{ item.key }}/live/ca.pem \
    --cert-file /etc/letsencrypt/{{ item.key }}/live/cert.pem \
    --fullchain-file /etc/letsencrypt/{{ item.key }}/live/fullchain.pem \
    --reloadcmd "sudo /bin/systemctl reload nginx.service"
  become: true
  become_user: acme
  with_dict: "{{ nginx_revproxy_sites }}"
  when: item.value.letsencrypt | default(False)
