- name: Copy Script to create token
  template:
    src: jwt_bash_script.sh.j2
    dest: /tmp/jwt_bash_script
    mode: +x
  become: false
  delegate_to: localhost

- name: Run JWT Create script
  shell: >
    bash /tmp/jwt_bash_script '{{ ngninx_revproxy_jwt_secret }}' {{ nginx_revproxy_jwt_payload }}
  no_log: true
  become: false
  delegate_to: localhost
  register: ngninx_revproxy_jwt_token
