- name: Create WebRoot sites
  file:
    dest: "/var/www/{{ item.name }}"
    mode: 0775
    state: directory
    owner: www-data
    group: www-data
  with_items: "{{ nginx_revproxy_sites }}"
  notify: Reload Nginx

- include_role:
    name: ansible-role-letsencrypt

- include_tasks: _create_sites.yml
  with_items: "{{ nginx_revproxy_sites }}"
